"""
Seed the MedInsight database with realistic synthetic data for demos.

Source of truth: MITRE Synthea output. The exact reproducible command that
produces the CSV consumed here is documented in backend/seed_data/synthea/README.md
(and in the file header of backend/seed_data/synthea/generate_patients.py).

What this command creates
-------------------------
* Patient records from Synthea's `patients.csv` demographics.
* A handful of Family groupings — some households are linked into real Family
  records (so the patient "Family" tab shows a member list), while other
  household clusters are intentionally left ungrouped so Step 4's "possible
  family" banner has real matches to show during a demo.
* Appointment records spread across past and upcoming dates with a realistic
  mix of statuses (scheduled / completed / cancelled / no_show).
* A few sample Documents attached to some patients (placeholder PDFs) so the
  document list and "Run OCR" button both have something to click.
* Dev login accounts (one admin, one doctor, one receptionist) created /
  verified, with documented credentials (see the README).

Idempotency / safety
--------------------
* Users are created only if they don't already exist (existing dev logins are
  reused, never clobbered).
* Patient/Family/Appointment/Document data is only written when the database is
  empty of patient data, OR when `--flush` is passed to wipe those tables first.
  This keeps the command safe to re-run during a demo without deleting the data
  you already created manually.

Mapping decisions (Synthea -> MedInsight) — documented for reviewers
--------------------------------------------------------------------
* full_name        = FIRST + " " + LAST
* date_of_birth    = BIRTHDATE (YYYYMMDD -> YYYY-MM-DD)
* gender           = Synthea GENDER ('M'/'F' / can be empty) -> model choices
                    male/female/other.
* address          = ADDRESS + ", " + CITY + " " + STATE  (Synthea splits street,
                    city, state into separate CSV columns; we re-join them for
                    the single free-text `address` field).
* phone            = Synthea's patients.csv has NO phone column. We derive a
                    deterministic phone per patient. All members of a household
                    (patients sharing an ADDRESS) are given the SAME phone so
                    Step 4's phone+address family-matching has real signal.
* email            = derived as first.last@example.medinsight.local (Synthea
                    doesn't export email addresses in the base CSV).
* blood_group      = Synthea has no blood type. Assigned pseudo-randomly from
                    Patient.BloodGroup choices as a reasonable synthetic default.
* allergies        = Synthea stores allergies in allergies.csv (a separate export),
                    not patients.csv. For simplicity we assign 0-2 realistic
                    allergies from a small curated pool as synthetic defaults.
* medical_history  = Synthea keeps diagnoses in conditions.csv. We synthesize a
                    short, age-appropriate medical-history note per patient so
                    the Medical History tab is populated. (Real condition imports
                    from conditions.csv are left for a future step.)

IMPORTANT
---------
ALL data produced here is synthetic, generated by / in the style of MITRE's
Synthea. It is NOT real patient data and must never be mistaken for PHI.
"""

from __future__ import annotations

import csv
import random
import re
from datetime import datetime, timedelta
from pathlib import Path

from django.contrib.auth import get_user_model
from django.core.files.base import ContentFile
from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

from appointments.models import Appointment
from documents.models import Document
from patients.models import Family, Patient

User = get_user_model()

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent  # backend/
DEFAULT_CSV = BASE_DIR / "seed_data" / "synthea" / "patients.csv"

# ── Curated synthetic pools (NOT real PHI) ──────────────────────────────────
ALLERGY_POOL = [
    "Penicillin",
    "Sulfa drugs",
    "Aspirin / NSAIDs",
    "Peanuts",
    "Shellfish",
    "Latex",
    "Ciprofloxacin",
    "Dust mites",
    "Pollen (seasonal)",
    "Ibuprofen",
]
BLOOD_GROUPS = [
    "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", "unknown",
]

DOC_TYPES = ["prescription", "lab_report", "invoice", "medical_record", "other"]

REASONS = [
    "Annual health check-up",
    "Follow-up consultation",
    "Chest pain evaluation",
    "Routine blood work",
    "Diabetes management review",
    "Blood pressure check",
    "Vaccination / immunization",
    "High fever and cough",
    "Headache / migraine consult",
    "Thyroid function review",
    "Skin rash evaluation",
    "Pre-operative assessment",
    "Gastrointestinal discomfort",
    "Joint pain / rheumatology consult",
]


def _parse_birthdate(raw: str):
    """Synthea BIRTHDATE is YYYYMMDD; convert to a date object (safe)."""
    raw = (raw or "").strip()
    if len(raw) == 8 and raw.isdigit():
        return datetime.strptime(raw, "%Y%m%d").date()
    if raw:
        # Fall back to an ISO-ish partial
        m = re.match(r"(\d{4})-(\d{2})-(\d{2})", raw)
        if m:
            return datetime(*[int(x) for x in m.groups()]).date()
    return None


def _clean_name(value: str) -> str:
    """Synthea name fields can be empty; fall back to a stable placeholder."""
    value = (value or "").strip()
    return value if value else "Unknown"


def load_patients_from_csv(path: Path) -> list[dict]:
    """Read Synthea `patients.csv` into a list of demographic dicts."""
    if not path.exists():
        raise CommandError(
            f"Synthea CSV not found at {path}. Run "
            "seed_data/synthea/generate_patients.py (or real Synthea) first."
        )

    patients = []
    with path.open("r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        for idx, row in enumerate(reader, start=1):
            first = _clean_name(row.get("FIRST"))
            last = _clean_name(row.get("LAST"))

            gender_raw = (row.get("GENDER") or "").strip().upper()
            if gender_raw.startswith("M"):
                gender = Patient.Gender.MALE
            elif gender_raw.startswith("F"):
                gender = Patient.Gender.FEMALE
            elif gender_raw in ("T", "F", "M"):
                gender = {  # noqa: SIM111
                    "T": Patient.Gender.OTHER,
                }.get(gender_raw, Patient.Gender.OTHER)
            else:
                gender = Patient.Gender.OTHER

            street = (row.get("ADDRESS") or "").strip()
            city = (row.get("CITY") or "").strip()
            state = (row.get("STATE") or "").strip()
            address_parts = [p for p in (street, city, state) if p]
            address = ", ".join(address_parts)

            patients.append(
                {
                    "synthea_id": (row.get("Id") or f"SYNTH{idx:04d}").strip(),
                    "full_name": f"{first} {last}".strip(),
                    "first": first,
                    "last": last,
                    "date_of_birth": _parse_birthdate(row.get("BIRTHDATE")),
                    "gender": gender,
                    "address": address,
                    "email": (
                        f"{re.sub(r'[^a-z0-9]+', '.', (first + ' ' + last).lower())}"
                        "@example.medinsight.local"
                    ),
                }
            )
    return patients


def _normalize_address(addr: str) -> str:
    """Case/space-fold an address so co-located patients group together."""
    return re.sub(r"\s+", " ", (addr or "").strip().lower())


def build_households(patients: list[dict]) -> dict[int, list[int]]:
    """
    Group patient indexes by normalized address. Households with more than one
    patient are co-located groups -> candidates for shared phones / families.
    """
    by_addr: dict[str, list[int]] = {}
    for i, p in enumerate(patients):
        by_addr.setdefault(_normalize_address(p["address"]), []).append(i)
    # Keep only groups of 2+; this collapses the intended households and any
    # coincidentally co-located patients into shared households.
    return {addr: idxs for addr, idxs in by_addr.items() if len(idxs) > 1}


def assign_phones(patients: list[dict], households: dict[int, list[int]]) -> None:
    """Assign each patient a deterministic phone; household members share one."""
    rng = random.Random(20260201)
    next_phone = rng.sample(range(10000000, 99999999), len(patients))
    next_phone_iter = iter(next_phone)

    used = set()
    for idxs in households.values():
        phone = f"98{next(next_phone_iter)}"  # shared household line
        for i in idxs:
            patients[i]["phone"] = phone
            used.add(i)
    for i in range(len(patients)):
        if i not in used:
            patients[i]["phone"] = f"98{next(next_phone_iter)}"


class Command(BaseCommand):
    help = (
        "Seed the database with Synthea-derived synthetic patients, families, "
        "appointments, documents, and dev login accounts. Pass --flush to wipe "
        "existing patient data before seeding."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--csv",
            type=str,
            default=None,
            help="Path to a Synthea patients.csv. Defaults to seed_data/synthea/patients.csv.",
        )
        parser.add_argument(
            "--flush",
            action="store_true",
            help="Delete existing Patient/Family/Appointment/Document rows before seeding.",
        )
        parser.add_argument(
            "--skip-documents",
            action="store_true",
            help="Skip creating sample documents (useful for very fast re-seeds).",
        )

    # ── Account seeding ─────────────────────────────────────────────────────
    def seed_dev_accounts(self, verbosity: int):
        """Ensure dev login accounts exist with documented credentials."""
        accounts = [
            # username, role, first, last, email, password
            ("admin",         "admin",        "System", "Admin",      "admin@medinsight.local",      "admin123!"),
            ("dr_patel",      "doctor",       "Anika",  "Patel",      "patel@medinsight.local",      "DoctorPass1!"),
            ("dr_kapoor",     "doctor",       "Sanjay", "Kapoor",     "kapoor@medinsight.local",     "DoctorPass1!"),
            ("reception",     "receptionist", "Maya",   "Gupta",      "reception@medinsight.local",  "ReceptionPass1!"),
        ]
        created = []
        for username, role, first, last, email, password in accounts:
            obj, was_created = User.objects.get_or_create(username=username)
            if was_created:
                obj.role = role
                obj.first_name = first
                obj.last_name = last
                obj.email = email
                obj.is_active = True
                obj.is_staff = role in ("admin",)
                obj.is_superuser = role == "admin"
                obj.set_password(password)
                obj.save()
                created.append(username)
            elif verbosity:
                self.stdout.write(f"  account exists (kept): {username} ({role})")
        if verbosity:
            reason = "created/updated:{created}".format(created=", ".join(created)) if created else "all already present"
            self.stdout.write(f"Dev accounts {reason}")
        return created

    # ── Family seeding ──────────────────────────────────────────────────────
    def create_families(
        self, patients: list[dict], households: dict[int, list[int]], verbosity: int
    ) -> None:
        """
        Turn a subset of the co-located household clusters into real Family
        records (so the Family tab shows a member list). The remaining clusters
        stay ungrouped so possible-family/ has banner matches to offer.
        """
        clusters = list(households.values())
        rng = random.Random(20260202)
        rng.shuffle(clusters)

        # Link roughly half the households into real families.
        for idxs in clusters[: max(1, len(clusters) // 2)]:
            members = [patients[i] for i in idxs]
            last_name = members[0]["last"] or "Family"
            fam = Family.objects.create(family_name=f"{last_name} Family")
            for m in members:
                m["family"] = fam
            if verbosity:
                self.stdout.write(
                    f"  family created: {fam.family_name} "
                    f"({', '.join(m['full_name'] for m in members)})"
                )

    # ── Patient seeding ─────────────────────────────────────────────────────
    def create_patients(self, patients: list[dict], verbosity: int) -> list[Patient]:
        created: list[Patient] = []
        rng = random.Random(20260203)
        for p in patients:
            patient_kwargs = {
                "full_name": p["full_name"],
                "date_of_birth": p["date_of_birth"],
                "gender": p["gender"],
                "phone": p.get("phone", ""),
                "email": p.get("email", ""),
                "address": p.get("address", ""),
                "blood_group": rng.choice(BLOOD_GROUPS),
                "family": p.get("family"),
            }
            # Allergies: 0-2 from the pool (synthetic default; Synthea patients.csv
            # has no allergy column — see module docstring).
            allergies = rng.sample(ALLERGY_POOL, k=rng.randint(0, 2))
            patient_kwargs["allergies"] = ", ".join(allergies)

            # Medical history: short age-appropriate note.
            patient_kwargs["medical_history"] = self._build_medical_history(p, rng)

            created.append(Patient.objects.create(**patient_kwargs))
        if verbosity:
            self.stdout.write(f"  patients created: {len(created)}")
        return created

    @staticmethod
    def _build_medical_history(p: dict, rng: random.Random) -> str:
        dob = p["date_of_birth"]
        age = ((timezone.localdate() - dob).days // 365) if dob else 30
        notes = []
        if age >= 50:
            notes = rng.sample(
                [
                    "Hypertension — managed on medication",
                    "Type 2 diabetes — diet-controlled",
                    "Hyperlipidemia — on statin therapy",
                    "Osteoarthritis of knees",
                    "Hypothyroidism — on levothyroxine",
                ],
                k=rng.randint(1, 2),
            )
        elif age >= 30:
            notes = rng.sample(
                ["Seasonal allergies", "Migraines (infrequent)", "Mild asthma", "Vitamin D deficiency"],
                k=rng.randint(0, 2),
            )
        else:
            notes = rng.sample(["No significant past medical history", "Childhood asthma (resolved)"], k=rng.randint(0, 1))
        return "; ".join(notes).strip() or "No significant past medical history on record."

    # ── Appointment seeding ─────────────────────────────────────────────────
    def create_appointments(self, patients, doctors, verbosity: int) -> int:
        today = timezone.localdate()
        rng = random.Random(20260204)
        count = 0

        # Roughly: 40% past (completed/no_show/cancelled), 15% today, 45% upcoming.
        for patient in patients:
            n_appts = rng.choice([0, 1, 1, 2])
            for _ in range(n_appts):
                kind = rng.random()
                if kind < 0.40:
                    offset = -rng.randint(1, 60)
                elif kind < 0.55:
                    offset = 0  # today
                else:
                    offset = rng.randint(1, 45)

                date = today + timedelta(days=offset)
                hour = rng.randint(9, 17)
                minute = rng.choice([0, 15, 30, 45])
                time = datetime(today.year, today.month, today.day, hour=hour, minute=minute).time()

                if offset < 0:
                    status = rng.choices(
                        [Appointment.Status.COMPLETED, Appointment.Status.NO_SHOW, Appointment.Status.CANCELLED],
                        weights=[80, 10, 10],
                    )[0]
                elif offset == 0:
                    status = rng.choices(
                        [Appointment.Status.SCHEDULED, Appointment.Status.COMPLETED, Appointment.Status.NO_SHOW],
                        weights=[60, 30, 10],
                    )[0]
                else:
                    status = Appointment.Status.SCHEDULED

                Appointment.objects.create(
                    patient=patient,
                    doctor=rng.choice(doctors),
                    date=date,
                    time=time,
                    reason=rng.choice(REASONS),
                    status=status,
                )
                count += 1
        if verbosity:
            self.stdout.write(f"  appointments created: {count}")
        return count

    # ── Document seeding ────────────────────────────────────────────────────
    def create_documents(self, patients, verbosity: int) -> int:
        rng = random.Random(20260205)
        count = 0
        for patient in rng.sample(list(patients), min(len(patients), 6)):
            doc_type = rng.choice(DOC_TYPES)
            filename = f"{doc_type}_{patient.id}.pdf"
            pdf_bytes = self._make_placeholder_pdf(
                patient=patient.full_name,
                doc_type=doc_type,
            )
            doc = Document(
                patient=patient,
                document_type=doc_type,
                tags=", ".join(rng.sample(["cardiology", "lab", "2026", "routine", "follow-up"], k=rng.randint(1, 3))),
                processing_status=Document.ProcessingStatus.UPLOADED,
            )
            doc.file.save(filename, ContentFile(pdf_bytes), save=True)
            count += 1
        if verbosity:
            self.stdout.write(f"  documents created: {count}")
        return count

    @staticmethod
    def _make_placeholder_pdf(patient: str, doc_type: str) -> bytes:
        """Return a tiny but valid single-page PDF with readable ASCII text."""
        # PDF content streams are latin-1; drop any non-ASCII glyphs (e.g. an
        # em-dash) and escape PDF string parentheses just in case.
        text = f"{doc_type.replace('_', ' ').title()} - MedInsight sample for {patient}"
        text = text.encode("latin-1", "ignore").decode("latin-1")
        text = text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
        # Minimal PDF object structure.
        content = (
            "BT /F1 18 Tf 50 750 Td (MedInsight Sample Document) Tj ET\n"
            "BT /F1 12 Tf 50 720 Td (%s) Tj ET\n" % text
        ).encode("latin-1")
        objects = []
        objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
        objects.append(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
        objects.append(
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>"
        )
        objects.append(b"<< /Length %d >>\nstream\n%s\nendstream" % (len(content), content))
        objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

        header = b"%PDF-1.4\n"
        body = header
        offsets = []
        for i, obj in enumerate(objects, start=1):
            offsets.append(len(body))
            body += b"%d 0 obj\n" % i + obj + b"\nendobj\n"
        xref_pos = len(body)
        body += b"xref\n0 %d\n" % (len(objects) + 1)
        body += b"0000000000 65535 f \n"
        for off in offsets:
            body += b"%010d 00000 n \n" % off
        body += (
            b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n"
            % (len(objects) + 1, xref_pos)
        )
        return body

    # ── Main ────────────────────────────────────────────────────────────────
    def handle(self, *args, **options):
        verbosity = options["verbosity"]
        flush = options["flush"]
        csv_path = Path(options["csv"]) if options["csv"] else DEFAULT_CSV

        # Guard: don't clobber existing patient data unless --flush is explicit.
        if Patient.objects.exists():
            if not flush:
                raise CommandError(
                    "Patient data already exists. Pass --flush to wipe existing "
                    "Patient/Family/Appointment/Document rows and re-seed."
                )
            Patient.objects.all().delete()
            Family.objects.all().delete()
            Appointment.objects.all().delete()
            Document.objects.all().delete()
            self.stdout.write("Flushed existing patient/family/appointment/document data.")

        self.stdout.write("Seeding MedInsight demo data (all synthetic) ...")

        # 1. Dev accounts
        self.seed_dev_accounts(verbosity)

        # 2. Patients + families from Synthea CSV
        people = load_patients_from_csv(csv_path)
        if not people:
            raise CommandError("No patients rows found in the Synthea CSV.")

        households = build_households(people)
        assign_phones(people, households)
        self.create_families(people, households, verbosity)
        patients = self.create_patients(people, verbosity)

        # 3. Appointments
        doctors = list(User.objects.filter(role="doctor"))
        if not doctors:
            self.stdout.write(self.style.WARNING("No doctor accounts; skipping appointments."))
            doctors = []
        else:
            self.create_appointments(patients, doctors, verbosity)

        # 4. Sample documents
        if options["skip_documents"]:
            if verbosity:
                self.stdout.write("  documents skipped (--skip-documents)")
        else:
            self.create_documents(patients, verbosity)

        self.stdout.write(
            self.style.SUCCESS(
                f"Done. Seeded {len(patients)} patients. All data is SYNTHETIC "
                "(Synthea) - not real PHI."
            )
        )
