# Generated by Django 6.1 on 2026-08-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_medicines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
